version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=8837726742550.dkr.ecr.us-east-1.amazonaws.com/webapp
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t webapp .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker tag webapp:latest 837726742550.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
      - docker push 837726742550.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
artifacts:
    files: imagedefinitions.json
